### ISSUE TITLE
won't start on raspbian with node v4

### ISSUE THREAD

**Issue by kb0thn** [aprsworld/wsBroadcast#33]
aprs@camZ7777 ~/wsBroadcast $ node ws-broadcast.js --help
module.js:338
    throw err;
    ^

Error: Cannot find module '/home/aprs/wsBroadcast/ws-broadcast.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by kb0thn** [comment]
apparently READEME.md documentation incorrect. ws-broadcast.js doesn't exist anymore

**Comment by kb0thn** [comment]
Now trying with server.js per David's verbal instruction. Now getting:

aprs@camZ7777 ~/wsBroadcast $ node server.js --help
module.js:338
    throw err;
    ^

Error: Cannot find module '@aprsworld/jsutils'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/aprs/wsBroadcast/DataManager.js:4:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
